//
// Created by Вадим on 22.05.2026.
//

#ifndef CYTEXLAB_CYTEXLAB_PLATFORM_SYSCALLS_CYTEXLAB_PLATFROM_OPERATORS_H
#define CYTEXLAB_CYTEXLAB_PLATFORM_SYSCALLS_CYTEXLAB_PLATFROM_OPERATORS_H

#include <CytexLab-Platform.Types.h>

inline LPVOID operator new (UINT64 size, LPVOID mem) {
    return mem;
}

#endif //CYTEXLAB_CYTEXLAB_PLATFORM_SYSCALLS_CYTEXLAB_PLATFROM_OPERATORS_H
